name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main   # run only when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/flask-app"

      - name: SSH into EC2 and restart app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/flask-app
            source flask-venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
